const productsList = [
    {id : 1, 
    brand : "IILA",
    descp : "Soft Pinch Tinted Oil",
    imgSrc : "https://www.sephora.com/productimages/sku/s2362168-main-zoom.jpg?imwidth=500",
    price : 19.99},
    {id : 2, 
        brand : "IILA",
        descp : "Super Serum Skin Tint SPF 40",
        imgSrc : "https://www.sephora.com/productimages/sku/s2333607-main-zoom.jpg?pb=allure-best-2020&imwidth=500",
        price : 48.00},
    {id : 3, 
        brand : "Rare Beauty by Selena Gomez",
        descp : "Soft Pinch Liquid Blush",
        imgSrc : "https://www.sephora.com/productimages/sku/s2518959-main-zoom.jpg?pb=allure-2022-bestofbeauty-badge&imwidth=500",
        price : 23.00},
    {id : 4, 
        brand : "Summer Fridays",
        descp : "Lip Butter Balm",
        imgSrc : "https://www.sephora.com/productimages/sku/s2495497-main-zoom.jpg?pb=2020-03-sephora-clean-2019&imwidth=500",
        price : 24.00},
    {id : 5, 
        brand : "Rare Beauty by Selena Gomez",
        descp : "Soft Pinch Tinted Lip Oil",
        imgSrc : "https://www.sephora.com/productimages/sku/s2640159-main-zoom.jpg?imwidth=500",
        price : 20.99},
    {id : 6, 
        brand : "Dior",
        descp : "Lip Glow Oil",
        imgSrc : "https://www.sephora.com/productimages/sku/s2316248-main-zoom.jpg?imwidth=500",
        price : 40.00},
    {id : 7, 
        brand : "PATRICK TA",
        descp : "Major Headlines Double-Take Creme & Powder Blush Duo",
        imgSrc : "https://www.sephora.com/productimages/sku/s2699353-main-zoom.jpg?imwidth=500",
        price : 36.00},
]

export default productsList

